[tool.poetry]
name = "rp2040-pio-emulator"
version = "0.84.0"
description = "RP2040 emulator for the testing and debugging of PIO programs"
authors = ["Nathan Young"]
license = "Apache-2.0"
repository = "https://github.com/NathanY3G/rp2040-pio-emulator"
readme = "README.md"
packages = [
    { include = "pioemu" }
]
keywords = [
    "rp2040",
    "rp2",
    "raspberry-pi-pico",
    "testing",
    "tdd",
    "debugging",
]

[tool.poetry.dependencies]
python = "^3.10.13"

[tool.poetry.dev-dependencies]
pylint = "3.2.2"
pytest = "8.2.1"
coverage = "7.5.1"
black = "24.4.2"
mypy = "1.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
